config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :users, only: [:index, :show, :edit, :update]
  post 'users/:id', to: 'users#show'
  root to: "lists#welcome"

  get "welcome", to: "lists#welcome"
  post 'lists/:id', to: 'lists#show'
  resources :lists

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/list.rb
class List < ApplicationRecord
  belongs_to :user

  has_one_attached :photo

  validates :password, presence: false
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable # I may delete :validatable..

  validates :email, presence: true, uniqueness: true
  validates :password, presence: true
  validates :name, presence: true, uniqueness: true

  has_many :lists, dependent: :destroy
  has_one_attached :photo
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?

  include Pundit

  def after_sign_in_path_for(resource)
    user_path(current_user) #redirection to current user page after login with devise
  end

  private

  def configure_permitted_parameters
    # For additional fields in app/views/devise/registrations/new.html.erb
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])

    # For additional in app/views/devise/registrations/edit.html.erb
    devise_parameter_sanitizer.permit(:account_update, keys: [:name])
  end

  def skip_pundit?
    devise_controller? || params[:controller] =~ /(^(rails_)?admin)|(^pages$)/
  end
end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController
  before_action :authenticate_user!

  def show
    @user = User.find(params[:id])
    @users = User.all
    @my_lists = current_user.lists.order(created_at: :desc) #List.where(user: current_user)
    @users.each do |user|
      @my_lists
    end
  end

  def dashboard
  end

end

app/controllers/lists_controller.rb
class ListsController < ApplicationController
  skip_before_action :authenticate_user!, only: [:welcome, :show]
  before_action :set_list, only: [:show, :edit, :update, :destroy]

  # GET /lists
  # GET /lists.json
  def welcome
    @lists = List.all
    @users = User.all
  end

  def index
    welcome
  end

  # GET /lists/1
  # GET /lists/1.json
  def show
    set_list
    authorize @list
  end

  # GET /lists/new
  def new
    @list = List.new
    authorize @list
  end

  # GET /lists/1/edit
  def edit
    authorize @list
  end

  # POST /lists
  # POST /lists.json
  def create
    @list = List.new(list_params)
    @list.user = current_user
    authorize @list
    if @list.save
      redirect_to @list, notice: 'List was successfully created.'
    else
      render :new
    end
  end

  # PATCH/PUT /lists/1
  # PATCH/PUT /lists/1.json
  def update
    authorize @list

    respond_to do |format|
      if @list.update(list_params)
        format.html { redirect_to @list, notice: 'List was successfully updated.' }
        format.json { render :show, status: :ok, location: @list }
      else
        format.html { render :edit }
        format.json { render json: @list.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /lists/1
  # DELETE /lists/1.json
  def destroy
    authorize @list
    @list.destroy
    respond_to do |format|
      format.html { redirect_to lists_url, notice: 'List was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_list
      @list = List.find(params[:id])

      authorize @list
    end

    # Only allow a list of trusted parameters through.
    def list_params
      params.require(:list).permit(:name, :style, :link, :content, :photo, :user_id)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!, only: [:show]
  def index
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
  end

  def edit
    @user = current_user
  end

  def update
    respond_to do |format|
      if current_user.update(user_params)
        format.html { redirect_to current_user, notice: 'Kudos! You updated your profile!' }
      else
        format.html { render :edit }
      end
    end
  end

  private

  def user_params
    params.require(:user).permit(
      :status,
      :fisrst_name,
      :last_name
    )
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def resource_name
    :user
  end

  def resource
    @resource ||= User.new
  end

  def resource_class
    User
  end

  def devise_mapping
    @devise_mapping ||= Devise.mappings[:user]
  end
end

app/helpers/lists_helper.rb
module ListsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/application/_favicon.html.erb
<link rel="apple-touch-icon" sizes="180x180" href="<%= asset_path 'favicon/apple-touch-icon.png' %>">
<link rel="icon" type="image/png" sizes="32x32" href="<%= asset_path 'favicon/favicon-32x32.png' %>">
<link rel="icon" type="image/png" sizes="16x16" href="<%= asset_path 'favicon/favicon-16x16.png' %>">
<link rel="manifest" href="<%= asset_path 'favicon/site.webmanifest' %>">
<link rel="mask-icon" href="<%= asset_path 'favicon/safari-pinned-tab.svg' %>" color="#080708">
<link rel="shortcut icon" href="<%= asset_path 'favicon/favicon.ico' %>">
<meta name="msapplication-TileColor" content="#000000">
<meta name="msapplication-config" content="<%= asset_path 'favicon/browserconfig.xml' %>">
<meta name="theme-color" content="#ffffff">

app/views/dashboard/dashboard.html.erb
<div>
  <div class="my-lists">
    <h1>THIS IS THE CORRECT DASHBOARD!</h1>
    <% @my_lists.each do |list| %>

    <%= link_to list.name, list_path(list) %>
    <% end %>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>


  <%= render 'application/favicon' %>


  <head>
    <title>Tunes Of Freedom ;)</title>

    <link href="https://fonts.googleapis.com/css2?family=Bangers&display=swap" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css2?family=Poiret+One&display=swap" rel="stylesheet">
    <!-- for the quote generator..-->
    <link rel='stylesheet' href='https://fonts.googleapis.com/css?family=Source+Code+Pro'>
    <link rel='stylesheet' href='https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.0.0-beta.2/css/bootstrap.css'>
    <script src='https://cdnjs.cloudflare.com/ajax/libs/jquery/3.2.1/jquery.min.js'></script>
    <script language="JavaScript" type="text/javascript" src="/js/jquery-1.2.6.min.js"></script>
    <script language="JavaScript" type="text/javascript" src="/js/jquery-ui-personalized-1.5.2.packed.js"></script>
    <script language="JavaScript" type="text/javascript" src="/js/sprinkle.js"></script>
    <!-- end here -->


    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>

    <style type = "text/css">
    </style>
  </head>

  <body>
    <%= render 'shared/login' %>
    <%= render 'shared/signup' %>
    <%= render 'shared/navbar' %>
    <%= render 'shared/banner' %>
    <%= yield %>
  </body>


  <div>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
  </div>

  <footer>
    <%= render 'shared/footer' %>
  </footer>

</html>

app/views/lists/_form.html.erb
<%= simple_form_for(list) do |f| %>
  <% if list.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(list.errors.count, "error") %> prohibited this list from being saved:</h2>

      <ul>
        <% list.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <%= f.input :name, as: :string %>
  <%= f.input :style, as: :string %>
  <%= f.input :link, as: :string %>
  <%= f.input :content, as: :text %>
  <div>
  <%= f.input :photo, as: :file %>
  <%= f.submit "create list" %>
  </div>
<% end %>

app/views/lists/edit.html.erb
<h1>Editing List</h1>

<%= render 'form', list: @list %>

<%= link_to 'Show', @list %> |
<%= link_to 'Back', lists_path %>

app/views/lists/index.html.erb
<p id="notice"><%= notice %></p>

<div class="container">
  <div id="lists">
    <h1>Lists</h1>

    <table>
      <thead>
        <tr>
          <th>Name</th>
          <th>Style</th>
          <th colspan="3"></th>
        </tr>
      </thead>

      <tbody>
        <% @lists.each do |list| %>
          <tr>
            <td><%= list.name %></td>
            <td><%= list.style %></td>
            <td><%= list.link %></td>

            <% if policy(list).edit? %>
              <td><%= link_to 'Show', list %></td>
              <td><%= link_to 'Edit', edit_list_path(list) %></td>
              <td><%= link_to 'Destroy', list, method: :delete, data: { confirm: 'Are you sure?' } %></td>
            <% end %>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>
</div>

<br>

<% if policy(List).create? %>
  <%= link_to 'New List', new_list_path %>
<% end %>

app/views/lists/new.html.erb
<h1>New List</h1>

<%= render 'form', list: @list %>

<%= link_to 'Back', lists_path %>

app/views/lists/show.html.erb
<p id="notice"><%= notice %></p>

<p class="neon-info">
  <%= @list.name %>
</p>

<p class="neon-info">
  <%= @list.style %>
</p>

<p class="neon-info">
  Link: <%= @list.link %>
</p>

<p class="neon-info">
  Description:
  <%= @list.content %>
</p>

<div id="list-photo">
  <div>
    Photo of the list..
  </div>
  <div>
    <%= cl_image_tag @list.photo.key, height: 432, width: 532, crop: :fit %>
  </div>
</div>

<div id="list-info">
  <h1 class="neon-info-big"><%= @list.name %></h1>
  <h3 class="neon-info-big"><%= @list.style %></h3>
</div>

<div class="item">
  <iframe width="560" height="315" src="<%= @list.link %>"
  frameborder="0" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>
</div>

<p class="neon-info">Made by <%= @list.user.name %> with love!</p>

<p class="neon-info">
  <%= link_to 'Edit', edit_list_path(@list) %> |
  <%= link_to 'Back', root_path %>
</p>


<% unless @list.user == current_user %>
  <%= link_to "Created by #{@list.user.name}", user_path(@list.user.id)%>
<% end %>

app/views/lists/welcome.html.erb
<div class="list-box" id="admin-box">
  <% if current_user && current_user.admin? %>
    <h1 id="admin-not">hello admin friend!</h1>
  <% elsif user_signed_in? %>
     <h1 id="admin-not">You are not the admin..</h1>
  <% else %>
    <h1 id="admin-not">sign in to save your lists</h1>
  <% end %>
</div>

<!-- Looper for every list! -->
<div class="list-box">

  <% User.first.lists.each do |list| %>
    <div id="landing-cards">
      <div class="neon-info">
        <%= list.name + " | " + list.style %>
      </div>

      <div id="listcard" class="btn-over-pic">
        <div class="click-me"><%= button_to "Listen to me!", list, class: "btn btn-success" %></div>
        <%= cl_image_tag list.photo.key, height: 432, width: 532, crop: :fit %>
      </div>
    </div>
  <% end %>
</div>

<!--Here comes the links to each user dashboard!-->

<div class="list-box">
  <% if User.present? %>
    <% @users.each do |user| %>
      <div id="usr-lists">
        <%= button_to user.name + "testing..(here should be link_to #{user.name} list!)", user_path(user.id), class: "btn btn-danger" %>
      </div>
    <% end %>
  <% else %>
    <p>doesn't work..</p>
  <% end %>
</div>

<!--trying to link to each user dashboard-->


<!--here ends the testing-ground-->

<% if policy(List).create? %>
  <%= link_to 'New List', new_list_path %>
<% end %>

app/views/shared/_banner.html.erb
<div class="master-div">
  <div class="banner" id="welcome-quote">
    <div class="neon-wrapper">
      <div class="neon-text">TUNES OF FREEDOM</div>
      <div class="container py-5" id="quote-div">
        <div class="output" id="output">
          <h1 class="cursor"></h1>
          <p></p>
        </div>
      </div>
    </div>
  </div>
</div>

<div id="style" class="container">
  <p>search for your style!</p>
  <a id="enter-btn" class="btn btn-danger" href="#"><span>search now</span></a>
</div>

app/views/shared/_footer.html.erb
<!--buy me a beer?-->
<script data-name="BMC-Widget" src="https://cdnjs.buymeacoffee.com/1.0.0/widget.prod.min.js"
 data-id="phaedonv" data-description="Support me on Buy me a coffee!" data-message="Thank you for visiting.
 You can now buy me a coffee.. or beer ;)" data-color="#BD5FFF" data-position="Right" data-x_margin="18" data-y_margin="18"></script>
<div class="footer">
  <div class="footer-link">
    <h2 id="ucon">under construction<a target="_blank" href="#"><i class="fab fa-facebook-square"></i></a></h2>
  </div>
  <div class="footer-copyright">
   <h3 id="footer-title"> Tunes of Freedom&copy;</h3>
  </div>
  <div>
    <script type="text/javascript" src="https://cdnjs.buymeacoffee.com/1.0.0/button.prod.min.js" data-name="bmc-button" data-slug="phaedonv"
    data-color="#BD5FFF" data-emoji="🍻"  data-font="Bree" data-text="Buy me a beer!" data-outline-color="#000000" data-font-color="#ffffff"
    data-coffee-color="#FFDD00" ></script>
  </div>

<div id="gh">
  <a id="github-link" href="https://github.com/phaedonv" target="_blank">
    <img alt="github" src="https://res.cloudinary.com/thisisnotanimage/image/upload/v1612975528/GitHub-Mark-Light-120px-plus_hra54k.png"
    width="63px" height="auto">
 </a>
</div>

</div>

app/views/shared/_login.html.erb
<!-- Button trigger modal
<button type="button" class="btn btn-primary btn-lg" data-toggle="modal" data-target="#myModal">
  Log in
</button>
-->

<!-- Modal -->
<div class="modal fade" id="myModal" data-backdrop="static" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
  <div class="modal-dialog modal-dialog-centered" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span>close</button>
        <!--<h4 class="modal-title" id="myModalLabel"> login window</h4>-->
      </div>
      <div class="modal-body">
        <!-- HERE COMES THE DEVISE FORM!!! !-->

        <div id="new-session">
          <div id="login_title">
            <h2>Log in hello</h2>
          </div>

          <div id="login-form">
            <%= form_for(resource, as: resource_name, url: session_path(resource_name)) do |f| %>
              <div class="field">
                <%= f.label :email %><br />
                <%= f.email_field :email, autofocus: true, autocomplete: "email" %>
              </div>

              <div class="field">
                <%= f.label :password %><br />
                <%= f.password_field :password, autocomplete: "current-password" %>
              </div>

              <% if devise_mapping.rememberable? %>
                <div class="field">
                  <%= f.check_box :remember_me %>
                  <%= f.label :remember_me %>
                </div>
              <% end %>
            </div>

            <div>
              <div class="actions" >
                <%= f.submit "Log in" %>
                <span data-toggle="modal" data-target="#myModal">
                  <%= link_to 'Sign up', new_user_registration_path, 'data-toggle' => "modal", 'data-target' => "#signup", class: "nav-link" %>
                </span>
              </div>

              <% render "devise/shared/links" %>
            </div>

          <% end %>

        </div>
      </div>
<!--
      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">Cancel</button>
        <button type="button" class="btn btn-primary" data-submit="modal">Save changes</button>
      </div>
-->
    </div>
  </div>
</div>

app/views/shared/_navbar.html.erb
<%= render 'shared/login' %>
<%= render 'shared/signup' %>

<div class="navbar navbar-expand-sm navbar-light navbar-lewagon" >
  <% if current_user %>
    <div>
      <%= cl_image_tag "https://res.cloudinary.com/thisisnotanimage/image/upload/v1595696199/Tunes%20of%20Freedom/mask-guy-neon-eye-th-2048x1152_yhrfg9.jpg", style: 'height:142px;width:142px;border-radius:50%;object-fit:cover;object-position:center;position:absolute;' %>
      <p id="welcome-msg">Welcome <%= current_user.name %>!<br>Enjoy your music.</p>
    </div>
  <% else %>
    <div data-toggle="modal" data-target="#myModal">
      <%= link_to '/users/sign_in', data: {remote: "true", toggle: "modal", target: "#modal"}, class: "navbar-brand", method: "get" do %>
        <%= cl_image_tag "https://res.cloudinary.com/thisisnotanimage/image/upload/v1595696199/Tunes%20of%20Freedom/mask-guy-neon-eye-th-2048x1152_yhrfg9.jpg", style: 'height:142px;width:142px;border-radius:50%;object-fit:cover;object-position:center;position:absolute;' %>
        <p id="welcome-msg">Sign in<br>to create your<br>own lists!</p>
      </div>
    <% end %>
  <% end %>



  <!--
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
-->



  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">

        <li class="nav-item active">
          <%= link_to "Home", root_path, class: "nav-link" %>
        </li>

        <li class="nav-item">
          <%= link_to "Lists", lists_path, class: "nav-link" %>
        </li>

        <% if user_signed_in? %>
        <div class="dropdown">
  <button class="btn btn-danger dropdown-toggle" type="button" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
    Settings
  </button>
  <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
    <%= link_to "Settings", root_path, class: "dropdown-item" %>
    <%= link_to "Activity", "#", class: "dropdown-item" %>
    <%= link_to "Log out", destroy_user_session_path, method: :delete, class: "dropdown-item" %>
  </div>
</div>
        <% else %>
          <li class="nav-item" data-toggle="modal" data-target="#myModal">
            <%= link_to "Login", '/users/sign_in', data: {remote: "true", toggle: "modal", target: "#login"}, class: "nav-link", method: "get" %>
          </li>
          <li class="nav-item" data-toggle="modal" data-target="#myModal">
            <%= link_to "Sign Up", '/users/sign_up', data: {remote: "true", toggle: "modal", target: "#signup"}, class: "nav-link", method: "get" %>
          </li>
        <% end %>

    </ul>
  </div>
</div>

app/views/shared/_signup.html.erb
<!-- Modal -->
<div class="modal fade" id="signup" data-backdrop="static" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
  <div class="modal-dialog modal-dialog-centered" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title" id="myModalLabel">Close sign up window</h4>
      </div>
      <div class="modal-body">
        <div class="background_white m-auto p-5 w80">
          <h2>Sign up</h2>

          <%= simple_form_for(resource, as: resource_name, url: registration_path(resource_name)) do |f| %>
            <%= f.error_notification %>

            <div class="form-inputs">
              <%= f.input :email,
                          required: true,
                          autofocus: true,
                          input_html: { autocomplete: "email" }%>
              <%= f.input :password,
                          required: true,
                          hint: ("#{@minimum_password_length} characters minimum" if @minimum_password_length),
                          input_html: { autocomplete: "new-password" } %>
              <%= f.input :password_confirmation,
                          required: true,
                          input_html: { autocomplete: "new-password" } %>
              <%= f.input :name,
                          required: true,
                          autofocus: true,
                          input_html: { autocomplete: "name" }%>
            </div>

            <div class="form-actions">
              <%= f.button :submit, "Sign up" %>
            </div>
          <% end %>

          <% render "devise/shared/links" %>
        </div>

      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
        <button type="button" class="btn btn-primary">Save changes</button>
      </div>
    </div>
  </div>
</div>

app/views/users/edit.html.erb
<h1>Users#edit</h1>
<p>Find me in app/views/users/edit.html.erb</p>

app/views/users/index.html.erb
<h1>Users#index</h1>

<div class="list-box">
  <% if User.present? %>
    <% @users.each do |user| %>
      <div id="usr-lists">
        <%= button_to user.name + "testing..(here should be link_to #{user.name} list!)", user_path(user.id), class: "btn btn-danger" %>
      </div>
    <% end %>
  <% else %>
    <p>doesn't work..</p>
  <% end %>
</div>

app/views/users/show.html.erb
<div class="container">

  <div id="dashboard">



    <h1><%= @user.first_name %> <%= @user.last_name %></h1>

    <hr style="background-color: #f91bb7;">

    <h4>Find me in app/views/users/show.html.erb</h4>

    <hr style="background-color: #f91bb7;">

    <h4>name | username: <%= @user.name %></h4>

    <h4>email: <%= @user.email %></h4>

    <h4>first name: <%= @user.first_name %></h4>

    <h4>last name: <%= @user.last_name %></h4>

    <h4>status: <%= @user.status %></h4>

  </div>

</div>